---
- name: Setup Tomcat
  hosts: all
  become: yes

  tasks:
    - name: Download Tomcat from Apache
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-11/v11.0.11/bin/apache-tomcat-11.0.11.tar.gz"
        dest: "/root/apache-tomcat-11.0.11.tar.gz"

    - name: Untar the Apache file
      command: tar -zxvf /root/apache-tomcat-11.0.11.tar.gz -C /root/

    - name: Rename the Tomcat directory
      command: mv /root/apache-tomcat-11.0.11 /root/tomcat

    - name: Install latest available Java
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Set roles in tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /root/tomcat/conf/tomcat-users.xml

    - name: Replace context.xml
      copy:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml

    - name: Create Tomcat systemd service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Server
          After=network.target

          [Service]
          User=root
          Group=root
          Type=forking
          Environment="JAVA_HOME=/usr/lib/jvm/jre"
          Environment="CATALINA_HOME=/root/tomcat"
          ExecStart=/root/tomcat/bin/startup.sh
          ExecStop=/root/tomcat/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: yes
